### ISSUE TITLE
web版での機能提案

### ISSUE THREAD

**Issue by GrandDukeShun** [Raclett3/Chunithm-Tools-2.0#4]
ブックマークレットのjsをワンタップでクリップボードに張り付けるボタンを付けると初回の登録作業がやりやすくなると思います

**Comment by Raclett3** [comment]
クリップボードに張り付けるよりは、下に同様の内容のハイパーリンクを用意することで、一部ブラウザでは直接これをブックマークに登録できますし、コピーも同様に楽に行えるかと思います。
